import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

// import {
//   Breadcrumb,
//   BreadcrumbItem,
//   BreadcrumbLink,
//   BreadcrumbList,
//   BreadcrumbPage,
//   BreadcrumbSeparator,
// } from "@/components/ui/breadcrumb";
import CustomAlert from "@/components/alertCustom/NotificationAlert";
import DynamicBreadcrumt from "@/components/breadcrumbt";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { AppSidebar } from "../components/app-sidebar";

import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "majodomo",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex">
              <SidebarProvider>
                <AppSidebar />
                <main className="w-full">
                  <CustomAlert
                  // type="destructive"
                  // leftIcon={TriangleAlert}
                  // rightIcon={CircleX}
                  // description="There are 2 errors with your submission"
                  />
                  <div className=" flex justify-between items-center">
                    <header className="flex h-16 shrink-0 items-center gap-2 px-4 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                      <SidebarTrigger className="-ml-1" />
                      {/* <Breadcrumb>
                        <BreadcrumbList>
                          <BreadcrumbItem className="hidden md:block">
                            <BreadcrumbLink href="/">
                              home
                            </BreadcrumbLink>
                          </BreadcrumbItem>
                          <BreadcrumbSeparator className="hidden md:block" />
                          <BreadcrumbItem>
                            <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                          </BreadcrumbItem>
                        </BreadcrumbList>
                      </Breadcrumb> */}
                      <DynamicBreadcrumt />
                    </header>
                    {/* <div className="px-4">
                      <ModeToggle />
                    </div> */}
                  </div>
                  {/* <Separator /> */}
                  <div className="w-full p-2">{children}</div>
                </main>
                <Toaster />
              </SidebarProvider>
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
